stages:       
  - test

unit-test-job:
  image: cypress/browsers   
  stage: test  
  script:
    - npm ci
    - npm install cypress-cucumber-preprocessor --save-dev
    - npm install mochawesome --save-dev
    - npm install --save-dev mochawesome mochawesome-merge mochawesome-report-generator cypress-mochawesome-reporter
    - npx cypress run
    - npx mochawesome-merge mochawesome-report/.jsons/*.json > mochawesome.json
    - npx mochawesome-report-generator mochawesome.json -o mochawesome-report/html
  artifacts:
    when: always
    paths:
      - mochawesome-report/html  # Path for the HTML report
      - cypress/screenshots      # Path for screenshots
      - cypress/videos 
    expire_in: 7 days
