stages:       

  - test

unit-test-job:
  image: cypress/browsers   
  stage: test  
  script:
    - npm init
    - npm install cypress --save-dev
    - npm install cypress-cucumber-preprocessor --save-dev
    - npm install mochawesome
    - npx cypress run --reporter mochawesome
  artifacts:
    when: always
    paths:
      - mochawesome-report/**
      - cypress/screenshots/**/*.png
      - cypress/videos/**/*.mp4
    expire_in: 7 days